version: '3'

volumes:
  mongodb_data:
    driver: local

networks:
  desafio_nest:
    name: api-db
    driver: bridge

services:
  app:
    image: fabiohsgomes/desafio02-nest
    ports:
      - 3000:3000
    networks:
      - desafio_nest
    depends_on:
      - db 
  db:
    image: bitnami/mongodb:5.0.17
    volumes:
      - mongodb_data:/bitnami/mongodb
    environment:
      MONGODB_ROOT_PASSWORD: root
      MONGODB_DATABASE: nest
    networks:
      - desafio_nest